### ISSUE TITLE
# Error: connection failed

### ISSUE THREAD

**Issue by vkuehn** [willbelr/bridge#1]
Hi,
just downloaded the latest version of bridge on a linux box when starting bridge.py I get

 Error: connection failed, available ports: /dev/ttyACM0, /dev/ttyprintk

this is with python3 ./bridge.py and  sudo python3 ./bridge.py
Version of Python is 3.4.3
The Serial device is an arduino which works nicely with arduino ide monitor or other serial termonal progams.
Any idea what the reason could be ?

**Comment by willbelr** [comment]
By default the port is set to /dev/ttyUSB0 (the most common port for arduinos). The error message tells you that you have two ports currently available, which are /dev/ttyACM0 and /dev/ttyprintk. The first is likely your arduino, and the second seems to be a printer.

All you have to do is to change the port (the text box in the top right corner) to /dev/ttyACM0 and it should work fine. You should not need to run the script with sudo. As with arduino IDE, on Linux you can grant access to your tty ports by adding your user to opt group, or with an udev rule.

Let me know how it turns out !
